language: python
python:
- '3.6'
services:
- mongodb
install: make setup
script: make test
deploy:
  provider: heroku
  app: certbrite
  api_key:
    secure: 11ouEbCI38V2NZ/0T6NV0yki3jGggCUo0H5/KKunEWY5z/cO0BDxZdfmGR8MMDwVJ8Yhyg3Bos8am6hD85JCWGKG4OTDRagumYAIVrZcHTPNlxzkk5M+dCRkBIKaHzzxrctFdnndWMMkEYHnVXNhJb1pmR9NBrSNiDlnCAgke4TUOzhP61uN38U6CfTBRVLmUkbf5vL7MPp6tI3Yf6UzLNr7em3sccnHoTV4LZPWDEIGfRM0nLs8ab3lmsXNKn0hXQtVUsdRCi3Wn2xizbQoJjpOJLg3drAjQ1YRWpQA1+6UfhcTVm6uLvgrxIPBbaXe4QXRq6CRBH6JiSnsCC8Zg0Pe9D29t7jULFQ3qUxyf1nWygIULaz0hsL+IUjQIXYCtBeaT29OHg7MgfrhHIkUrGos9v9eGHLGGWCqN12rSpsLCzKM82Z+bf8mqy9NCVLroMBN2R+UWfAtNHWurzrGab/QCAn2bMOuZwNI7pu4bHKhyZ5e46PIdvlR1qRMR8O1tG0PM2HdqkZssrVKz3JHXjJZavF+Uj4MDpFctWjsLNvHL+SDEzBqrqbmNqkS+k7vKsIWL3/jyWGpqkqk9Tj0IZzI2IXvCbscBSize2zw7qkVOYuKmWA6Bg7h5hBKUOkgsQ59c9vM/eHxX4aBeaGRAgT2B3/1JDqjmQPJQKJDIe0=
